// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package corpus

import (
	"bytes"
	"fmt"
	"strings"
	"testing"

	bircodec "ballerina-lang-go/bir/codec"
	"ballerina-lang-go/context"
	"ballerina-lang-go/semtypes"
	"ballerina-lang-go/test_util"
)

// TestBIRSerializationRoundtrip compiles .bal files to BIR, serializes the BIR, deserializes it
// with a fresh compiler context, executes the deserialized BIR, and validates the output matches
// the expected integration test output.
// TestBIRSerializationRoundtrip skip list (autogenerated by migration tooling).
// Each entry is a path under corpus/bal/. To re-evaluate, remove the entry, run the
// failing test with -update, and inspect the diff.
var birSerializationRoundtripSkipList = []string{
	// Compilation panics, preventing this stage from running.
	"subset8/08-bug/listfill1-v.bal",
	"subset8/08-decimal/tofloat4-p.bal",
	"subset8/08-decimal/toint13-p.bal",
	"subset8/08-fill/11-v.bal",
	"subset8/08-fill/12-v.bal",
	"subset8/08-fill/19-v.bal",
	"subset8/08-fill/20-v.bal",
	"subset8/08-fill/fill4-p.bal",
	"subset8/08-fill/order-v.bal",
	"subset8/08-list/fixedlength1-v.bal",
	"subset8/08-list/fixedlength2-v.bal",
	"subset8/08-nested/exact1-p.bal",
	"subset8/08-nested/proj1-p.bal",
	"subset8/08-rest/exact1-p.bal",
	"subset8/08-tuple/comp9-v.bal",
	"subset8/08-typecast/2-p.bal",
	"subset8/08-typecast/6-p.bal",

	// parse errors
	"subset8/08-decimal/eq1-v.bal",
	"subset8/08-decimal/vardecl1-v.bal",
	"subset8/08-fill/17-v.bal",

	// BIR serialization roundtrip produces different output (state leak through unmarshal).
	"subset8/08-bug/fill2-p.bal",
	"subset8/08-bug/fill2-v.bal",
	"subset8/08-bug/fill3-v.bal",
	"subset8/08-bytearr/1-v.bal",
	"subset8/08-fill/1-v.bal",
	"subset8/08-fill/13-v.bal",
	"subset8/08-fill/14-p.bal",
	"subset8/08-fill/16-v.bal",
	"subset8/08-fill/2-v.bal",
	"subset8/08-fill/3-v.bal",
	"subset8/08-fill/4-v.bal",
	"subset8/08-fill/5-v.bal",
	"subset8/08-fill/6-v.bal",
	"subset8/08-fill/8-v.bal",
	"subset8/08-fill/9-p.bal",
	"subset8/08-list/1-p.bal",
	"subset8/08-list/boolean2-v.bal",
	"subset8/08-list/float4-v.bal",
	"subset8/08-list/int6-v.bal",
	"subset8/08-list/string-v.bal",
	"subset8/08-nested/fill2-v.bal",
	"subset8/08-nested/fill3-p.bal",
}

func TestBIRSerializationRoundtrip(t *testing.T) {
	testPairs := test_util.GetTests(t, test_util.Integration, func(path string) bool {
		return strings.HasSuffix(path, "-v.bal") || strings.HasSuffix(path, "-p.bal")
	})

	for _, testPair := range testPairs {
		t.Run(testPair.Name, func(t *testing.T) {
			t.Parallel()
			testBIRSerializationRoundtrip(t, testPair)
		})
	}
}

func testBIRSerializationRoundtrip(t *testing.T, testPair test_util.TestCase) {
	for _, skip := range birSerializationRoundtripSkipList {
		if strings.HasSuffix(testPair.InputPath, skip) {
			t.Skipf("Skipping BIR serialization roundtrip test for %s", testPair.InputPath)
			return
		}
	}

	if isTestSkipped(testPair) {
		t.Skipf("Skipping BIR serialization roundtrip test for %s", testPair.InputPath)
	}

	defer func() {
		if r := recover(); r != nil {
			t.Errorf("panic during BIR serialization roundtrip for %s: %v", testPair.InputPath, r)
		}
	}()

	// Step 1: Compile .bal to BIR.
	var stdoutBuf, stderrBuf bytes.Buffer
	birPkg, _, compileErr := runCompilePhase(testPair.InputPath, &stdoutBuf, &stderrBuf)
	if birPkg == nil || compileErr != nil {
		t.Fatalf("compilation failed for %s: %v", testPair.InputPath, compileErr)
	}

	// Step 2: Serialize BIR.
	serialized, err := bircodec.Marshal(birPkg)
	if err != nil {
		t.Fatalf("BIR serialization failed for %s: %v", testPair.InputPath, err)
	}

	// Step 3: Deserialize with a fresh compiler context.
	freshEnv := context.NewCompilerEnvironment(semtypes.CreateTypeEnv(), false)
	freshCtx := context.NewCompilerContext(freshEnv)
	deserialized, err := bircodec.Unmarshal(freshCtx, serialized)
	if err != nil {
		t.Fatalf("BIR deserialization failed for %s: %v", testPair.InputPath, err)
	}

	// Step 4: Execute the deserialized BIR.
	var rtStdoutBuf, rtStderrBuf bytes.Buffer
	runInterpretPhase(deserialized, &rtStdoutBuf, &rtStderrBuf)

	// Step 5: Compare against expected output.
	expectedStdout, expectedStderr, err := test_util.LoadTxtarStdoutStderr(testPair.ExpectedPath)
	if err != nil {
		t.Fatalf("failed to load expected from %s: %v", testPair.ExpectedPath, err)
	}

	result := evaluateTestResult(expectedStdout, expectedStderr, rtStdoutBuf.String(), rtStderrBuf.String())
	if result.success {
		return
	}

	stdoutMismatch := result.expectedStdout != result.actualStdout
	stderrMismatch := result.expectedStderr != normalizeIntegrationStderr(result.actualStderr)

	var msg strings.Builder
	if stdoutMismatch {
		fmt.Fprintf(&msg, "stdout mismatch\n%s", test_util.FormatExpectedGot(result.expectedStdout, result.actualStdout))
	}
	if stderrMismatch {
		if msg.Len() > 0 {
			msg.WriteString("\n\n")
		}
		fmt.Fprintf(&msg, "stderr mismatch\n%s", test_util.FormatExpectedGot(
			normalizeIntegrationStderr(result.expectedStderr),
			normalizeIntegrationStderr(result.actualStderr),
		))
	}
	t.Errorf("%s", msg.String())
}
