// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package bir_test

import (
	"flag"
	"os"
	"strings"
	"testing"

	"ballerina-lang-go/bir"
	"ballerina-lang-go/context"
	"ballerina-lang-go/semtypes"
	"ballerina-lang-go/test_util"
	"ballerina-lang-go/test_util/testphases"

	"github.com/sergi/go-diff/diffmatchpatch"
)

var supportedSubsets = []string{"subset1"}

var update = flag.Bool("update", false, "update expected BIR text files")

// readExpectedBIRText reads the expected BIR text file and returns its content.
// Returns the content and an error. If the file doesn't exist, the error will be os.ErrNotExist.
func readExpectedBIRText(filePath string) (string, error) {
	expectedTextBytes, err := os.ReadFile(filePath)
	if err != nil {
		return "", err
	}
	return string(expectedTextBytes), nil
}

// getBIRDiff generates a detailed diff string showing differences between expected and actual BIR text.
func getBIRDiff(expectedText, actualText string) string {
	dmp := diffmatchpatch.New()
	diffs := dmp.DiffMain(expectedText, actualText, false)
	return dmp.DiffPrettyText(diffs)
}

// TestBIRGeneration tests BIR generation from .bal source files in the corpus.
// TestBIRGeneration skip list (autogenerated by migration tooling).
// Each entry is a path under corpus/bal/. To re-evaluate, remove the entry, run the
// failing test with -update, and inspect the diff.
var birGenerationSkipList = []string{
	// BIR generation fails upstream of this stage.
	"subset8/08-bug/charcast1-v.bal",
	"subset8/08-bug/charcast2-v.bal",
	"subset8/08-const/10-v.bal",
	"subset8/08-const/7-v.bal",
	"subset8/08-const/8-v.bal",
	"subset8/08-decimal/tofloat3-v.bal",
	"subset8/08-decimal/tofloat4-p.bal",
	"subset8/08-decimal/toint13-p.bal",
	"subset8/08-error/10-v.bal",
	"subset8/08-error/check1-v.bal",
	"subset8/08-error/check10-v.bal",
	"subset8/08-error/check3-v.bal",
	"subset8/08-fill/chain2-v.bal",
	"subset8/08-fill/fill2-v.bal",
	"subset8/08-fill/fill3-v.bal",
	"subset8/08-fill/fill4-p.bal",
	"subset8/08-fill/fill7-v.bal",
	"subset8/08-future/fieldexpr1-v.bal",
	"subset8/08-future/lib1-v.bal",
	"subset8/08-future/main2-v.bal",
	"subset8/08-future/never-v.bal",
	"subset8/08-future/xmlsubtype-v.bal",
	"subset8/08-ifelse/ifelse4-v.bal",
	"subset8/08-mapping/5-v.bal",
	"subset8/08-match/float3-v.bal",
	"subset8/08-nested/exact1-p.bal",
	"subset8/08-nested/proj1-p.bal",
	"subset8/08-nested/push1-v.bal",
	"subset8/08-rest/construct7-v.bal",
	"subset8/08-rest/exact1-p.bal",
	"subset8/08-singleton/proj4-v.bal",
	"subset8/08-singleton/typecast1-v.bal",
	"subset8/08-string/10-v.bal",
	"subset8/08-string/11-v.bal",
	"subset8/08-string/12-v.bal",
	"subset8/08-string/13-v.bal",
	"subset8/08-string/15-v.bal",
	"subset8/08-string/16-v.bal",
	"subset8/08-string/17-v.bal",
	"subset8/08-tuple/push2-v.bal",
	"subset8/08-tuple/tupleunion1-v.bal",
	"subset8/08-typecast/11-v.bal",
	"subset8/08-typecast/12-v.bal",
	"subset8/08-typecast/16-v.bal",
	"subset8/08-typecast/2-p.bal",
	"subset8/08-typecast/6-p.bal",
	"subset8/08-union/construct4-v.bal",

	// parse errors
	"subset8/08-function/intersection11-v.bal",
	"subset8/08-function/intersection13-v.bal",
	"subset8/08-list/compoundassign1-v.bal",
	"subset8/08-match/2-v.bal",

	// Fixed-length array type descriptors (e.g. `int[5]`) not yet supported.
	"subset8/08-bug/listfill1-v.bal",
	"subset8/08-fill/11-v.bal",
	"subset8/08-fill/12-v.bal",
	"subset8/08-fill/19-v.bal",
	"subset8/08-fill/20-v.bal",
	"subset8/08-fill/order-v.bal",
	"subset8/08-list/fixedlength1-v.bal",
	"subset8/08-list/fixedlength2-v.bal",
	"subset8/08-tuple/comp9-v.bal",

	// Runtime panic in this stage on the migrated test.

	// Table-type descriptors not yet supported.
}

func TestBIRGeneration(t *testing.T) {
	flag.Parse()

	testPairs := test_util.GetValidAndPanicTests(t, test_util.BIR)

	for _, testPair := range testPairs {
		t.Run(testPair.Name, func(t *testing.T) {
			t.Parallel()
			testBIRGeneration(t, testPair)
		})
	}
}

// testBIRGeneration tests BIR generation for a single .bal file.
func testBIRGeneration(t *testing.T, testPair test_util.TestCase) {
	for _, skip := range birGenerationSkipList {
		if strings.HasSuffix(testPair.InputPath, skip) {
			t.Skipf("Skipping BIR generation test for %s", testPair.InputPath)
			return
		}
	}

	// Catch panics during BIR generation
	defer func() {
		if r := recover(); r != nil {
			t.Errorf("panic while generating BIR from %s: %v", testPair.InputPath, r)
		}
	}()

	env := context.NewCompilerEnvironment(semtypes.CreateTypeEnv(), false)
	cx := context.NewCompilerContext(env)
	result, err := testphases.RunPipeline(cx, testphases.PhaseBIR, testPair.InputPath)
	if err != nil {
		t.Errorf("pipeline failed for %s: %v", testPair.InputPath, err)
		return
	}

	if result.BIRPackage == nil {
		t.Errorf("BIR package is nil for %s", testPair.InputPath)
		return
	}

	verifyBIRPositions(t, result.BIRPackage, testPair.InputPath)

	// Pretty print BIR output
	prettyPrinter := bir.PrettyPrinter{}
	actualBIR := prettyPrinter.Print(*result.BIRPackage)

	// If update flag is set, update expected file
	if *update {
		if test_util.UpdateIfNeeded(t, testPair.ExpectedPath, actualBIR) {
			t.Fatalf("Updated expected BIR file: %s", testPair.ExpectedPath)
		}
		return
	}

	// Read expected BIR text file
	expectedText := test_util.ReadExpectedFile(t, testPair.ExpectedPath)

	// Compare BIR text strings exactly
	if actualBIR != expectedText {
		diff := getBIRDiff(expectedText, actualBIR)
		t.Errorf("BIR text mismatch for %s\nExpected file: %s\n%s", testPair.InputPath, testPair.ExpectedPath, diff)
		return
	}
}

func verifyBIRPositions(t *testing.T, pkg *bir.BIRPackage, inputPath string) {
	for _, fn := range pkg.Functions {
		verifyFunctionPositions(t, &fn, inputPath)
	}
	if pkg.MainFunction != nil {
		verifyFunctionPositions(t, pkg.MainFunction, inputPath)
	}
}

func verifyFunctionPositions(t *testing.T, fn *bir.BIRFunction, inputPath string) {
	for _, bb := range fn.BasicBlocks {
		for _, inst := range bb.Instructions {
			if bir.IsLocationEmpty(inst.GetPos()) {
				t.Errorf("instruction %T in %s (BB: %s) has no position info for %s", inst, fn.Name, bb.Id, inputPath)
			}
		}
		if bb.Terminator != nil && bir.IsLocationEmpty(bb.Terminator.GetPos()) {
			t.Errorf("terminator %T in %s (BB: %s) has no position info for %s", bb.Terminator, fn.Name, bb.Id, inputPath)
		}
	}
}
