# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  path_filters:
    - "!bir/testdata/**/*.txt"
    - "!bir/testdata/**/*.bir"
    - "!bir/testdata/**/*.json"
    - "!corpus/**/*.txt"
