// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package desugar_test

import (
	"flag"
	"testing"

	"ballerina-lang-go/ast"
	"ballerina-lang-go/context"
	"ballerina-lang-go/model"
	"ballerina-lang-go/semtypes"
	"ballerina-lang-go/test_util"
	"ballerina-lang-go/test_util/testphases"
	"ballerina-lang-go/tools/diagnostics"

	"github.com/sergi/go-diff/diffmatchpatch"
)

var update = flag.Bool("update", false, "update expected desugared AST files")

// TestDesugar skip list (autogenerated by migration tooling).
// Each entry is a path under corpus/bal/. To re-evaluate, remove the entry, run the
// failing test with -update, and inspect the diff.
var desugarSkipList = []string{
	"subset8/08-fill/chain2-v.bal",
	"subset8/08-future/fieldexpr1-v.bal",
	"subset8/08-mapping/5-v.bal",
	"subset8/08-nested/bdd1-v.bal",
	"subset8/08-rest/exact1-p.bal",
	"subset8/08-singleton/proj4-v.bal",
	"subset8/08-union/construct4-v.bal",
	"subset8/08-colon/field1-v.bal",
	"subset8/08-mapping/8-v.bal",
	"subset8/08-mutate/record1-v.bal",
	// Source uses syntax pi does not yet parse (compilation unit nil).
	"subset8/08-function/intersection11-v.bal",
	"subset8/08-function/intersection13-v.bal",
	"subset8/08-list/compoundassign1-v.bal",
	"subset8/08-match/2-v.bal",
	"subset8/08-semtype/not1-v.bal",
	"subset8/08-semtype/objectCompliment-v.bal",
	"subset8/08-semtype/proj10-v.bal",
	"subset8/08-semtype/proj2-v.bal",
	"subset8/08-semtype/proj3-v.bal",
	"subset8/08-semtype/proj7-v.bal",
	"subset8/08-semtype/proj8-v.bal",

	// Desugar panics on an unsupported construct.
	"subset8/08-semtype/recurse-v.bal",
	"subset8/08-semtype/xml-complex-ro-v.bal",
	"subset8/08-semtype/xml-complex-rw-v.bal",
	"subset8/08-semtype/xml-never-v.bal",
	"subset8/08-semtype/xml-readonly-v.bal",
	"subset8/08-semtype/xml-sequence-v.bal",

	// Fixed-length array type descriptors (e.g. `int[5]`) not yet supported.
	"subset8/08-bug/listfill1-v.bal",
	"subset8/08-fill/11-v.bal",
	"subset8/08-fill/12-v.bal",
	"subset8/08-fill/19-v.bal",
	"subset8/08-fill/20-v.bal",
	"subset8/08-fill/order-v.bal",
	"subset8/08-list/fixedlength1-v.bal",
	"subset8/08-list/fixedlength2-v.bal",
	"subset8/08-semtype/fixed-length-array-large-v.bal",
	"subset8/08-semtype/fixed-length-array-readonly-v.bal",
	"subset8/08-semtype/fixed-length-array-tuple-readonly-v.bal",
	"subset8/08-semtype/fixed-length-array-tuple-v.bal",
	"subset8/08-semtype/fixed-length-array-tuple2-v.bal",
	"subset8/08-semtype/fixed-length-array-v.bal",
	"subset8/08-semtype/fixed-length-array2-v.bal",
	"subset8/08-semtype/proj6-v.bal",
	"subset8/08-semtype/proj9-v.bal",
	"subset8/08-tuple/comp9-v.bal",

	// AST node missing source position info.
	"subset8/08-semtype/object-v.bal",
	"subset8/08-semtype/objectRecursion-v.bal",

	// Table-type descriptors not yet supported.
	"subset8/08-semtype/anydata-v.bal",
	"subset8/08-semtype/table-readonly-v.bal",
	"subset8/08-semtype/table-v.bal",
	"subset8/08-semtype/table2-v.bal",
	"subset8/08-semtype/table3-v.bal",

	// AST node type not yet handled by this stage.
	"subset8/08-semtype/function-v.bal",
	"subset8/08-semtype/vararg-v.bal",
}

func TestDesugar(t *testing.T) {
	flag.Parse()

	testPairs := test_util.GetValidAndPanicTests(t, test_util.Desugar)

	for _, testPair := range testPairs {
		t.Run(testPair.Name, func(t *testing.T) {
			t.Parallel()
			testDesugar(t, testPair)
		})
	}
}

type walkTestVisitor struct {
	t *testing.T
}

func (v *walkTestVisitor) Visit(node ast.BLangNode) ast.Visitor {
	if node == nil {
		return nil
	}

	if diagnostics.IsLocationEmpty(node.GetPosition()) {
		v.t.Errorf("node with missing position: %T", node)
	}

	return v
}

func (v *walkTestVisitor) VisitTypeData(typeData *model.TypeData) ast.Visitor {
	return v
}

func testDesugar(t *testing.T, testCase test_util.TestCase) {
	for _, skip := range desugarSkipList {
		if test_util.HasPathSuffix(testCase.InputPath, skip) {
			t.Skipf("Skipping desugar test for %s", testCase.InputPath)
			return
		}
	}

	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("Desugar panicked for %s: %v", testCase.InputPath, r)
		}
	}()

	env := context.NewCompilerEnvironment(semtypes.CreateTypeEnv(), false)
	cx := context.NewCompilerContext(env)
	result, err := testphases.RunPipeline(cx, testphases.PhaseDesugar, testCase.InputPath)
	if err != nil {
		t.Errorf("pipeline failed for %s: %v", testCase.InputPath, err)
		return
	}

	// Serialize AST after desugaring
	prettyPrinter := ast.PrettyPrinter{}
	actualAST := prettyPrinter.Print(result.Package)

	// If update flag is set, update expected file
	if *update {
		if test_util.UpdateIfNeeded(t, testCase.ExpectedPath, actualAST) {
			t.Errorf("updated expected desugared AST file: %s", testCase.ExpectedPath)
		}
		return
	}

	// Read expected AST file
	expectedAST := test_util.ReadExpectedFile(t, testCase.ExpectedPath)

	// Compare AST strings exactly
	if actualAST != expectedAST {
		t.Errorf("Desugared AST mismatch for %s\nExpected file: %s\n%s",
			testCase.InputPath, testCase.ExpectedPath, getDiff(expectedAST, actualAST))
		return
	}

	visitor := &walkTestVisitor{t: t}
	ast.Walk(visitor, result.CompilationUnit)

	t.Logf("Desugar completed successfully for %s", testCase.InputPath)
}

func getDiff(expectedAST, actualAST string) string {
	dmp := diffmatchpatch.New()
	diffs := dmp.DiffMain(expectedAST, actualAST, false)
	return dmp.DiffPrettyText(diffs)
}
