// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
//
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Package registry loads embedded platform module symbols (langlib, standard library)
// from lib/registry/gen/*.sym. Artifacts are generated by tools/gen-embedded-libs and
// embedded at link time; see embed.go.
package registry

import (
	"sync"

	"ballerina-lang-go/context"
	"ballerina-lang-go/model"
	"ballerina-lang-go/model/symbolpool"
)

// ID identifies an org/module pair for a Ballerina library.
type ID struct {
	OrgName    string
	ModuleName string
}

// Module provides lazily loaded exported symbols for one embedded platform module.
type Module struct {
	Symbols func(*context.CompilerEnvironment) (model.ExportedSymbolSpace, error)
}

var (
	mu      sync.RWMutex
	modules = make(map[ID]Module)
)

// Register installs a module (low-level; embed.go uses RegisterEmbedded).
func Register(id ID, m Module) {
	mu.Lock()
	defer mu.Unlock()
	if _, exists := modules[id]; exists {
		panic("registry: duplicate register " + id.OrgName + "/" + id.ModuleName)
	}
	modules[id] = m
}

func cachedSymbolsFromBytes(symBytes []byte) func(*context.CompilerEnvironment) (model.ExportedSymbolSpace, error) {
	var cache sync.Map
	return func(env *context.CompilerEnvironment) (model.ExportedSymbolSpace, error) {
		if v, ok := cache.Load(env); ok {
			return v.(model.ExportedSymbolSpace), nil
		}
		exported, err := symbolpool.Unmarshal(env, symBytes)
		if err != nil {
			return model.ExportedSymbolSpace{}, err
		}
		cache.Store(env, exported)
		return exported, nil
	}
}

// RegisterEmbedded registers serialized exported symbols for a platform module.
func RegisterEmbedded(id ID, symBytes []byte) {
	Register(id, Module{Symbols: cachedSymbolsFromBytes(symBytes)})
}

// LoadSymbols returns exported symbols for id when registered; ok is false if unknown.
func LoadSymbols(env *context.CompilerEnvironment, id ID) (model.ExportedSymbolSpace, bool, error) {
	mu.RLock()
	m, ok := modules[id]
	mu.RUnlock()
	if !ok || m.Symbols == nil {
		return model.ExportedSymbolSpace{}, false, nil
	}
	exp, err := m.Symbols(env)
	if err != nil {
		return model.ExportedSymbolSpace{}, true, err
	}
	applyExportedTypeSemtypes(id.ModuleName, exp)
	return exp, true, nil
}
