// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package semantics_test

import (
	"flag"
	"strings"
	"testing"

	"ballerina-lang-go/ast"
	"ballerina-lang-go/context"
	"ballerina-lang-go/model"
	"ballerina-lang-go/semantics"
	"ballerina-lang-go/semtypes"
	"ballerina-lang-go/test_util"
	"ballerina-lang-go/test_util/testphases"
)

// TestSymbolResolver skip list (autogenerated by migration tooling).
// Each entry is a path under corpus/bal/. To re-evaluate, remove the entry, run the
// failing test with -update, and inspect the diff.
var symbolResolverSkipList = []string{
	// Source uses syntax pi does not yet parse (compilation unit nil).
	"subset8/08-function/intersection11-v.bal",
	"subset8/08-function/intersection13-v.bal",
	"subset8/08-list/compoundassign1-v.bal",
	"subset8/08-match/2-v.bal",
	"subset8/08-semtype/not1-v.bal",
	"subset8/08-semtype/objectCompliment-v.bal",
	"subset8/08-semtype/proj10-v.bal",
	"subset8/08-semtype/proj2-v.bal",
	"subset8/08-semtype/proj3-v.bal",
	"subset8/08-semtype/proj7-v.bal",
	"subset8/08-semtype/proj8-v.bal",

	// Fixed-length array type descriptors (e.g. `int[5]`) not yet supported.
	"subset8/08-bug/listfill1-v.bal",
	"subset8/08-fill/11-v.bal",
	"subset8/08-fill/12-v.bal",
	"subset8/08-fill/19-v.bal",
	"subset8/08-fill/20-v.bal",
	"subset8/08-fill/order-v.bal",
	"subset8/08-list/fixedlength1-v.bal",
	"subset8/08-list/fixedlength2-v.bal",
	"subset8/08-semtype/fixed-length-array-large-v.bal",
	"subset8/08-semtype/fixed-length-array-readonly-v.bal",
	"subset8/08-semtype/fixed-length-array-tuple-readonly-v.bal",
	"subset8/08-semtype/fixed-length-array-tuple-v.bal",
	"subset8/08-semtype/fixed-length-array-tuple2-v.bal",
	"subset8/08-semtype/fixed-length-array-v.bal",
	"subset8/08-semtype/fixed-length-array2-v.bal",
	"subset8/08-semtype/proj6-v.bal",
	"subset8/08-semtype/proj9-v.bal",
	"subset8/08-tuple/comp9-v.bal",

	// Runtime panic in this stage on the migrated test.
	"subset8/08-semtype/xml-complex-ro-v.bal",
	"subset8/08-semtype/xml-complex-rw-v.bal",
	"subset8/08-semtype/xml-never-v.bal",
	"subset8/08-semtype/xml-readonly-v.bal",
	"subset8/08-semtype/xml-sequence-v.bal",

	// Table-type descriptors not yet supported.
	"subset8/08-semtype/anydata-v.bal",
	"subset8/08-semtype/table-readonly-v.bal",
	"subset8/08-semtype/table-v.bal",
	"subset8/08-semtype/table2-v.bal",
	"subset8/08-semtype/table3-v.bal",

	// unknown_symbol
	"subset8/08-bug/charcast1-v.bal",
	"subset8/08-bug/charcast2-v.bal",
	"subset8/08-future/lib1-v.bal",
	"subset8/08-future/xmlsubtype-v.bal",
	"subset8/08-semtype/array-v.bal",
}

func TestSymbolResolver(t *testing.T) {
	flag.Parse()
	testPairs := test_util.GetValidAndPanicTests(t, test_util.AST)

	for _, testPair := range testPairs {
		t.Run(testPair.Name, func(t *testing.T) {
			t.Parallel()
			testSymbolResolution(t, testPair)
		})
	}
}

func testSymbolResolution(t *testing.T, testCase test_util.TestCase) {
	for _, skip := range symbolResolverSkipList {
		if strings.HasSuffix(testCase.InputPath, skip) {
			t.Skipf("Skipping symbol resolver test for %s", testCase.InputPath)
			return
		}
	}

	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("Symbol resolution panicked for %s: %v", testCase.InputPath, r)
		}
	}()

	env := context.NewCompilerEnvironment(semtypes.CreateTypeEnv(), false)
	cx := context.NewCompilerContext(env)
	result, err := testphases.RunPipeline(cx, testphases.PhaseSymbolResolution, testCase.InputPath)
	if err != nil {
		t.Errorf("pipeline failed for %s: %v", testCase.InputPath, err)
		return
	}
	if cx.HasErrors() {
		t.Fatalf("compiler context has errors for %s: %v", testCase.InputPath, cx.Diagnostics())
	}
	validator := &symbolResolutionValidator{t: t, testPath: testCase.InputPath}
	ast.Walk(validator, result.Package)
	// If we reach here, symbol resolution completed without panicking
	t.Logf("Symbol resolution completed successfully for %s", testCase.InputPath)
}

type symbolResolutionValidator struct {
	t        *testing.T
	testPath string
}

func (v *symbolResolutionValidator) Visit(node ast.BLangNode) ast.Visitor {
	if node == nil {
		return nil
	}
	if invocation, ok := node.(*ast.BLangInvocation); ok {
		if semantics.IsDeferredMethodSymbol(invocation.RawSymbol) {
			return nil
		}
	}
	// Check if this node should have a symbol resolved
	if nodeWithSymbol, ok := node.(ast.BNodeWithSymbol); ok {
		if !ast.SymbolIsSet(nodeWithSymbol) {
			v.t.Errorf("Symbol not resolved for %T at %s in %s",
				node, node.GetPosition(), v.testPath)
		}
	}
	if nodeWithScope, ok := node.(ast.NodeWithScope); ok {
		if nodeWithScope.Scope() == nil {
			v.t.Errorf("Scope not set for %T at %s in %s",
				node, node.GetPosition(), v.testPath)
		}
	}
	return v
}

func (v *symbolResolutionValidator) VisitTypeData(typeData *model.TypeData) ast.Visitor {
	if typeData.TypeDescriptor == nil {
		return nil
	}
	// Check if this type descriptor should have a symbol resolved
	if typeWithSymbol, ok := typeData.TypeDescriptor.(ast.BNodeWithSymbol); ok {
		if !ast.SymbolIsSet(typeWithSymbol) {
			v.t.Errorf("Symbol not resolved for type %T at %s in %s",
				typeData.TypeDescriptor, typeData.TypeDescriptor.GetPosition(), v.testPath)
		}
	}
	return v
}
