// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package semantics_test

import (
	"ballerina-lang-go/ast"
	"ballerina-lang-go/context"
	"ballerina-lang-go/model"
	"ballerina-lang-go/semtypes"
	"ballerina-lang-go/test_util"
	"ballerina-lang-go/test_util/testphases"
	"flag"
	"path/filepath"
	"strings"
	"testing"
)

// TestSemanticAnalysis skip list (autogenerated by migration tooling).
// Each entry is a path under corpus/bal/. To re-evaluate, remove the entry, run the
// failing test with -update, and inspect the diff.
var semanticAnalysisSkipList = []string{
	// Source uses syntax pi does not yet parse (compilation unit nil).
	"subset8/08-function/intersection11-v.bal",
	"subset8/08-function/intersection13-v.bal",
	"subset8/08-match/2-v.bal",

	// Fixed-length array type descriptors (e.g. `int[5]`) not yet supported.
	"subset8/08-fill/11-v.bal",
	"subset8/08-fill/12-v.bal",
	"subset8/08-fill/19-v.bal",
	"subset8/08-fill/20-v.bal",
	"subset8/08-fill/order-v.bal",

	// Migrated test uses a feature pi does not yet support in this stage.
	"subset8/08-bug/charcast1-v.bal",
	"subset8/08-bug/charcast2-v.bal",
	"subset8/08-const/10-v.bal",
	"subset8/08-const/7-v.bal",
	"subset8/08-const/8-v.bal",
	"subset8/08-decimal/tofloat3-v.bal",
	"subset8/08-error/10-v.bal",
	"subset8/08-error/check1-v.bal",
	"subset8/08-error/check10-v.bal",
	"subset8/08-error/check3-v.bal",
	"subset8/08-error/check7-p.bal",
	"subset8/08-fill/chain2-v.bal",
	"subset8/08-fill/fill2-v.bal",
	"subset8/08-fill/fill3-v.bal",
	"subset8/08-fill/fill4-p.bal",
	"subset8/08-fill/fill7-v.bal",
	"subset8/08-future/fieldexpr1-v.bal",
	"subset8/08-future/lib1-v.bal",
	"subset8/08-future/main2-v.bal",
	"subset8/08-future/never-v.bal",
	"subset8/08-future/xmlsubtype-v.bal",
	"subset8/08-ifelse/ifelse4-v.bal",
	"subset8/08-mapping/5-v.bal",
	"subset8/08-match/float3-v.bal",
	"subset8/08-nested/exact1-p.bal",
	"subset8/08-nested/proj1-p.bal",
	"subset8/08-nested/push1-v.bal",
	"subset8/08-rest/construct7-v.bal",
	"subset8/08-rest/exact1-p.bal",
	"subset8/08-singleton/proj4-v.bal",
	"subset8/08-singleton/typecast1-v.bal",
	"subset8/08-string/10-v.bal",
	"subset8/08-string/11-v.bal",
	"subset8/08-string/12-v.bal",
	"subset8/08-string/13-v.bal",
	"subset8/08-string/15-v.bal",
	"subset8/08-string/16-v.bal",
	"subset8/08-string/17-v.bal",
	"subset8/08-tuple/push2-v.bal",
	"subset8/08-tuple/tupleunion1-v.bal",
	"subset8/08-union/construct4-v.bal",

	// Table-type descriptors not yet supported.
}

func TestSemanticAnalysis(t *testing.T) {
	flag.Parse()

	testPairs := test_util.GetValidAndPanicTests(t, test_util.AST)

	for _, testPair := range testPairs {
		t.Run(testPair.Name, func(t *testing.T) {
			t.Parallel()
			testSemanticAnalysis(t, testPair)
		})
	}
}

func testSemanticAnalysis(t *testing.T, testCase test_util.TestCase) {
	for _, skip := range semanticAnalysisSkipList {
		if strings.HasSuffix(testCase.InputPath, skip) {
			t.Skipf("Skipping semantic analysis test for %s", testCase.InputPath)
			return
		}
	}

	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("Semantic analysis panicked for %s: %v", testCase.InputPath, r)
		}
	}()

	env := context.NewCompilerEnvironment(semtypes.CreateTypeEnv(), false)
	cx := context.NewCompilerContext(env)
	result, err := testphases.RunPipeline(cx, testphases.PhaseCFGAnalysis, testCase.InputPath)
	if err != nil {
		t.Errorf("pipeline failed for %s: %v", testCase.InputPath, err)
		return
	}
	if cx.HasErrors() {
		t.Fatalf("compiler context has errors for %s: %v", testCase.InputPath, cx.Diagnostics())
	}

	// Validate that all expressions have determinedTypes set
	validator := &semanticAnalysisValidator{t: t, ctx: cx}
	ast.Walk(validator, result.Package)

	// If we reach here, semantic analysis completed without panicking
	t.Logf("Semantic analysis completed successfully for %s", testCase.InputPath)
}

type semanticAnalysisValidator struct {
	t   *testing.T
	ctx *context.CompilerContext
}

func (v *semanticAnalysisValidator) Visit(node ast.BLangNode) ast.Visitor {
	if node == nil {
		return nil
	}

	// Check if node implements BLangExpression interface
	if expr, ok := node.(ast.BLangExpression); ok {
		// Validate determinedType is set
		if semtypes.IsNever(expr.GetDeterminedType()) {
			v.t.Errorf("determinedType is never for expression %T at %v",
				node, node.GetPosition())
		}
	} else {
		if node.GetDeterminedType() == nil {
			v.t.Errorf("determinedType not set for expression %T at %v",
				node, node.GetPosition())
		}
	}

	// Check if node has a symbol that should have type set
	if nodeWithSymbol, ok := node.(ast.BNodeWithSymbol); ok {
		symbol := nodeWithSymbol.Symbol()
		if v.ctx.SymbolType(symbol) == nil {
			v.t.Errorf("symbol %s (kind: %v) does not have type set for node %T at %v",
				v.ctx.SymbolName(symbol), v.ctx.SymbolKind(symbol), node, node.GetPosition())
		}
	}

	return v
}

func (v *semanticAnalysisValidator) VisitTypeData(typeData *model.TypeData) ast.Visitor {
	if typeData == nil || typeData.TypeDescriptor == nil {
		return v
	}

	// Check if type descriptor has a symbol that should have type set
	if typeWithSymbol, ok := typeData.TypeDescriptor.(ast.BNodeWithSymbol); ok {
		symbol := typeWithSymbol.Symbol()
		if v.ctx.SymbolType(symbol) == nil {
			v.t.Errorf("symbol %s (kind: %v) does not have type set for type descriptor %T at %v",
				v.ctx.SymbolName(symbol), v.ctx.SymbolKind(symbol), typeData.TypeDescriptor, typeData.TypeDescriptor.GetPosition())
		}
	}

	return v
}

var semanticAnalysisErrorSkipList = []string{
	// Expected error: got nothing.
	"subset8/08-bitwise/complement3-e.bal",
	"subset8/08-bug/assignforeach-e.bal",
	"subset8/08-bug/init2-e.bal",
	"subset8/08-bug/intersect1-e.bal",
	"subset8/08-bug/intersect2-e.bal",
	"subset8/08-bug/main2-e.bal",
	"subset8/08-bug/matchwild1-e.bal",
	"subset8/08-bug/stringop1-e.bal",
	"subset8/08-bug/unusedimport-e.bal",
	"subset8/08-compoundassign/9-e.bal",
	"subset8/08-const/1-e.bal",
	"subset8/08-const/10-e.bal",
	"subset8/08-const/11-e.bal",
	"subset8/08-const/12-e.bal",
	"subset8/08-const/13-e.bal",
	"subset8/08-const/14-e.bal",
	"subset8/08-const/15-e.bal",
	"subset8/08-const/16-e.bal",
	"subset8/08-const/17-e.bal",
	"subset8/08-const/18-e.bal",
	"subset8/08-const/22-e.bal",
	"subset8/08-const/23-e.bal",
	"subset8/08-const/4-e.bal",
	"subset8/08-const/5-e.bal",
	"subset8/08-const/6-e.bal",
	"subset8/08-const/7-e.bal",
	"subset8/08-const/8-e.bal",
	"subset8/08-const/9-e.bal",
	"subset8/08-decimal/add2-e.bal",
	"subset8/08-decimal/add3-e.bal",
	"subset8/08-decimal/add4-e.bal",
	"subset8/08-decimal/add5-e.bal",
	"subset8/08-decimal/add6-e.bal",
	"subset8/08-decimal/const5-e.bal",
	"subset8/08-decimal/const6-e.bal",
	"subset8/08-decimal/div2-e.bal",
	"subset8/08-decimal/div3-e.bal",
	"subset8/08-decimal/div4-e.bal",
	"subset8/08-decimal/fromfloat2-e.bal",
	"subset8/08-decimal/fromfloat3-e.bal",
	"subset8/08-decimal/mul2-e.bal",
	"subset8/08-decimal/mul3-e.bal",
	"subset8/08-decimal/mul4-e.bal",
	"subset8/08-decimal/mul5-e.bal",
	"subset8/08-decimal/rem3-e.bal",
	"subset8/08-decimal/rem4-e.bal",
	"subset8/08-decimal/sub2-e.bal",
	"subset8/08-decimal/sub3-e.bal",
	"subset8/08-decimal/toint2-e.bal",
	"subset8/08-decimal/toint3-e.bal",
	"subset8/08-decimal/toint4-e.bal",
	"subset8/08-decimal/toint5-e.bal",
	"subset8/08-decimal/toint6-e.bal",
	"subset8/08-equal/3-e.bal",
	"subset8/08-equal/4-e.bal",
	"subset8/08-equal/5-e.bal",
	"subset8/08-error/check8-e.bal",
	"subset8/08-fill/10-e.bal",
	"subset8/08-fill/15-e.bal",
	"subset8/08-fill/18-e.bal",
	"subset8/08-fill/21-e.bal",
	"subset8/08-fill/22-e.bal",
	"subset8/08-float/15-e.bal",
	"subset8/08-float/5-e.bal",
	"subset8/08-float/7-e.bal",
	"subset8/08-hex/decimal1-e.bal",
	"subset8/08-inclusive/compoundassign3-e.bal",
	"subset8/08-inclusive/construct5-e.bal",
	"subset8/08-inclusive/duplicate2-e.bal",
	"subset8/08-inclusive/fieldlvalue5-e.bal",
	"subset8/08-infinite/infiniteRecord4-e.bal",
	"subset8/08-list/17-e.bal",
	"subset8/08-list/6-e.bal",
	"subset8/08-list/compoundassign5-e.bal",
	"subset8/08-list/fixedlength1-e.bal",
	"subset8/08-list/fixedlength2-e.bal",
	"subset8/08-list/fixedlength3-e.bal",
	"subset8/08-list/fixedlength4-e.bal",
	"subset8/08-list/fixedlength5-e.bal",
	"subset8/08-list/fixedlength6-e.bal",
	"subset8/08-list/fixedlength7-e.bal",
	"subset8/08-list/fixedlength8-e.bal",
	"subset8/08-list/fixedlength9-e.bal",
	"subset8/08-map/compoundassign-e.bal",
	"subset8/08-mapping/14-e.bal",
	"subset8/08-mapping/4-e.bal",
	"subset8/08-mapping/6-e.bal",
	"subset8/08-mapping/7-e.bal",
	"subset8/08-match/19-e.bal",
	"subset8/08-match/3-e.bal",
	"subset8/08-match/7-e.bal",
	"subset8/08-narrowing/10-e.bal",
	"subset8/08-narrowing/11-e.bal",
	"subset8/08-narrowing/12-e.bal",
	"subset8/08-narrowing/15-e.bal",
	"subset8/08-narrowing/2-e.bal",
	"subset8/08-narrowing/4-e.bal",
	"subset8/08-narrowing/5-e.bal",
	"subset8/08-narrowing/6-e.bal",
	"subset8/08-narrowing/8-e.bal",
	"subset8/08-narrowing/if18-e.bal",
	"subset8/08-narrowing/unreach3-e.bal",
	"subset8/08-narrowing/unreach4-e.bal",
	"subset8/08-nillifting/compound1-e.bal",
	"subset8/08-nillifting/compound10-e.bal",
	"subset8/08-nillifting/compound11-e.bal",
	"subset8/08-nillifting/compound12-e.bal",
	"subset8/08-nillifting/compound2-e.bal",
	"subset8/08-nillifting/compound3-e.bal",
	"subset8/08-nillifting/compound4-e.bal",
	"subset8/08-nillifting/compound5-e.bal",
	"subset8/08-nillifting/compound6-e.bal",
	"subset8/08-nillifting/compound7-e.bal",
	"subset8/08-nillifting/compound8-e.bal",
	"subset8/08-nillifting/compound9-e.bal",
	"subset8/08-record/assign1-e.bal",
	"subset8/08-record/compoundassign4-e.bal",
	"subset8/08-record/fieldlvalue6-e.bal",
	"subset8/08-singleton/decimal10-e.bal",
	"subset8/08-singleton/decimal11-e.bal",
	"subset8/08-singleton/decimal12-e.bal",
	"subset8/08-singleton/decimal13-e.bal",
	"subset8/08-singleton/decimal2-e.bal",
	"subset8/08-singleton/decimal4-e.bal",
	"subset8/08-singleton/decimal5-e.bal",
	"subset8/08-singleton/decimal6-e.bal",
	"subset8/08-singleton/decimal7-e.bal",
	"subset8/08-singleton/decimal8-e.bal",
	"subset8/08-singleton/decimal9-e.bal",
	"subset8/08-singleton/nil1-e.bal",
	"subset8/08-singleton/not1-e.bal",
	"subset8/08-singleton/string1-e.bal",
	"subset8/08-singleton/stringconcat1-e.bal",
	"subset8/08-string/1-e.bal",
	"subset8/08-string/5-e.bal",
	"subset8/08-typecast/8-e.bal",
	"subset8/08-unused/unused1-e.bal",
	"subset8/08-unused/unused2-e.bal",
	"subset8/08-unused/unused3-e.bal",
	"subset8/08-unused/unused4-e.bal",
	"subset8/08-unused/unused5-e.bal",
	"subset8/08-unused/unused6-e.bal",

	// Runtime panic during semantic-error analysis.
}

func TestSemanticAnalysisErrors(t *testing.T) {
	flag.Parse()

	testPairs := test_util.GetErrorTests(t, test_util.AST)

	for _, testPair := range testPairs {
		t.Run(testPair.Name, func(t *testing.T) {
			t.Parallel()
			testSemanticAnalysisError(t, testPair)
		})
	}
}

func testSemanticAnalysisError(t *testing.T, testCase test_util.TestCase) {
	if shouldSkipSemanticAnalysisErrorTest(testCase.InputPath) {
		t.Skipf("Skipping semantic analysis error test for %s", testCase.InputPath)
		return
	}

	env := context.NewCompilerEnvironment(semtypes.CreateTypeEnv(), false)
	cx := context.NewCompilerContext(env)

	defer func() {
		if r := recover(); r != nil {
			t.Errorf("Semantic analysis panicked for %s: %v", testCase.InputPath, r)
		}

		if !cx.HasDiagnostics() {
			t.Errorf("Expected compile-time diagnostics for %s, but no diagnostics were recorded", testCase.InputPath)
			return
		}

		t.Logf("Compile-time diagnostic correctly detected for %s", testCase.InputPath)
	}()

	_, _ = testphases.RunPipeline(cx, testphases.PhaseCFGAnalysis, testCase.InputPath)

	// If we reach here without panic, the defer will catch it
}

func shouldSkipSemanticAnalysisErrorTest(inputPath string) bool {
	normalizedInputPath := filepath.ToSlash(inputPath)
	for _, skip := range semanticAnalysisErrorSkipList {
		normalizedSkipPath := filepath.ToSlash(skip)
		if strings.HasSuffix(normalizedInputPath, normalizedSkipPath) {
			return true
		}
	}
	return false
}
