// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package semantics_test

import (
	"flag"
	"strings"
	"testing"

	"ballerina-lang-go/context"
	"ballerina-lang-go/semantics"
	"ballerina-lang-go/semtypes"
	"ballerina-lang-go/test_util"
	"ballerina-lang-go/test_util/testphases"

	"github.com/sergi/go-diff/diffmatchpatch"
)

var updateCFG = flag.Bool("update", false, "update expected CFG text files")

// TestCFGGeneration tests CFG generation from .bal source files in the corpus.
// TestCFGGeneration skip list (autogenerated by migration tooling).
// Each entry is a path under corpus/bal/. To re-evaluate, remove the entry, run the
// failing test with -update, and inspect the diff.
var cfgGenerationSkipList = []string{
	// CFG could not be built (likely upstream stage error).
	"subset8/08-bug/charcast1-v.bal",
	"subset8/08-bug/charcast2-v.bal",
	"subset8/08-const/10-v.bal",
	"subset8/08-const/7-v.bal",
	"subset8/08-const/8-v.bal",
	"subset8/08-decimal/tofloat3-v.bal",
	"subset8/08-error/10-v.bal",
	"subset8/08-fill/chain2-v.bal",
	"subset8/08-fill/fill2-v.bal",
	"subset8/08-fill/fill3-v.bal",
	"subset8/08-fill/fill4-p.bal",
	"subset8/08-fill/fill7-v.bal",
	"subset8/08-future/fieldexpr1-v.bal",
	"subset8/08-future/lib1-v.bal",
	"subset8/08-future/never-v.bal",
	"subset8/08-future/xmlsubtype-v.bal",
	"subset8/08-mapping/5-v.bal",
	"subset8/08-match/float3-v.bal",
	"subset8/08-nested/exact1-p.bal",
	"subset8/08-nested/proj1-p.bal",
	"subset8/08-nested/push1-v.bal",
	"subset8/08-rest/construct7-v.bal",
	"subset8/08-rest/exact1-p.bal",
	"subset8/08-singleton/proj4-v.bal",
	"subset8/08-singleton/typecast1-v.bal",
	"subset8/08-string/10-v.bal",
	"subset8/08-string/11-v.bal",
	"subset8/08-string/12-v.bal",
	"subset8/08-string/13-v.bal",
	"subset8/08-string/15-v.bal",
	"subset8/08-string/16-v.bal",
	"subset8/08-string/17-v.bal",
	"subset8/08-tuple/push2-v.bal",
	"subset8/08-tuple/tupleunion1-v.bal",
	"subset8/08-union/construct4-v.bal",

	// Source uses syntax pi does not yet parse (compilation unit nil).
	"subset8/08-function/intersection11-v.bal",
	"subset8/08-function/intersection13-v.bal",
	"subset8/08-match/2-v.bal",

	// Fixed-length array type descriptors (e.g. `int[5]`) not yet supported.
	"subset8/08-fill/11-v.bal",
	"subset8/08-fill/12-v.bal",
	"subset8/08-fill/19-v.bal",
	"subset8/08-fill/20-v.bal",
	"subset8/08-fill/order-v.bal",

	// Runtime panic in this stage on the migrated test.

	// Table-type descriptors not yet supported.
}

func TestCFGGeneration(t *testing.T) {
	flag.Parse()

	testPairs := test_util.GetValidAndPanicTests(t, test_util.CFG)

	for _, testPair := range testPairs {
		t.Run(testPair.Name, func(t *testing.T) {
			t.Parallel()
			testCFGGeneration(t, testPair)
		})
	}
}

// testCFGGeneration tests CFG generation for a single .bal file.
func testCFGGeneration(t *testing.T, testPair test_util.TestCase) {
	for _, skip := range cfgGenerationSkipList {
		if strings.HasSuffix(testPair.InputPath, skip) {
			t.Skipf("Skipping CFG generation test for %s", testPair.InputPath)
			return
		}
	}

	// Catch panics during CFG generation
	defer func() {
		if r := recover(); r != nil {
			t.Errorf("panic while generating CFG from %s: %v", testPair.InputPath, r)
		}
	}()

	env := context.NewCompilerEnvironment(semtypes.CreateTypeEnv(), false)
	cx := context.NewCompilerContext(env)
	result, err := testphases.RunPipeline(cx, testphases.PhaseCFG, testPair.InputPath)
	if err != nil {
		t.Errorf("pipeline failed for %s: %v", testPair.InputPath, err)
		return
	}

	cfg := result.CFG
	if cfg == nil {
		t.Errorf("CFG is nil for %s", testPair.InputPath)
		return
	}

	// Validate backedgeParents is a subset of parents for every block
	for _, err := range cfg.ValidateInvariants() {
		t.Errorf("CFG invariant violated in %s: function %v, block %d: backedgeParent %d is not in parents %v",
			testPair.InputPath, err.FuncRef, err.BlockID, err.BackedgeParent, err.Parents)
	}

	// Pretty print CFG output
	prettyPrinter := semantics.NewCFGPrettyPrinter(cx)
	actualCFG := prettyPrinter.Print(cfg)

	// If update flag is set, update expected file
	if *updateCFG {
		if test_util.UpdateIfNeeded(t, testPair.ExpectedPath, actualCFG) {
			t.Fatalf("Updated expected CFG file: %s", testPair.ExpectedPath)
		}
		return
	}

	// Read expected CFG text file
	expectedText := test_util.ReadExpectedFile(t, testPair.ExpectedPath)

	// Compare CFG text strings exactly
	if actualCFG != expectedText {
		diff := getCFGDiff(expectedText, actualCFG)
		t.Errorf("CFG text mismatch for %s\nExpected file: %s\n%s", testPair.InputPath, testPair.ExpectedPath, diff)
		return
	}
}

// getCFGDiff generates a detailed diff string showing differences between expected and actual CFG text.
func getCFGDiff(expectedText, actualText string) string {
	dmp := diffmatchpatch.New()
	diffs := dmp.DiffMain(expectedText, actualText, false)
	return dmp.DiffPrettyText(diffs)
}
