// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package semantics_test

import (
	"flag"
	"testing"

	"ballerina-lang-go/ast"
	"ballerina-lang-go/context"
	"ballerina-lang-go/model"
	"ballerina-lang-go/semtypes"
	"ballerina-lang-go/test_util"
	"ballerina-lang-go/test_util/testphases"
)

// TestTypeResolver skip list (autogenerated by migration tooling).
// Each entry is a path under corpus/bal/. To re-evaluate, remove the entry, run the
// failing test with -update, and inspect the diff.
var typeResolverSkipList = []string{
	"subset8/08-nested/bdd1-v.bal",
	"subset8/08-colon/field1-v.bal",
	"subset8/08-mapping/8-v.bal",
	"subset8/08-mutate/record1-v.bal",
	// Source uses syntax pi does not yet parse (compilation unit nil).
	"subset8/08-function/intersection11-v.bal",
	"subset8/08-function/intersection13-v.bal",
	"subset8/08-list/compoundassign1-v.bal",
	"subset8/08-match/2-v.bal",
	"subset8/08-semtype/not1-v.bal",
	"subset8/08-semtype/objectCompliment-v.bal",
	"subset8/08-semtype/proj10-v.bal",
	"subset8/08-semtype/proj2-v.bal",
	"subset8/08-semtype/proj3-v.bal",
	"subset8/08-semtype/proj7-v.bal",
	"subset8/08-semtype/proj8-v.bal",

	// Fixed-length array type descriptors (e.g. `int[5]`) not yet supported.
	"subset8/08-bug/listfill1-v.bal",
	"subset8/08-fill/11-v.bal",
	"subset8/08-fill/12-v.bal",
	"subset8/08-fill/19-v.bal",
	"subset8/08-fill/20-v.bal",
	"subset8/08-fill/order-v.bal",
	"subset8/08-list/fixedlength1-v.bal",
	"subset8/08-list/fixedlength2-v.bal",
	"subset8/08-semtype/fixed-length-array-large-v.bal",
	"subset8/08-semtype/fixed-length-array-readonly-v.bal",
	"subset8/08-semtype/fixed-length-array-tuple-readonly-v.bal",
	"subset8/08-semtype/fixed-length-array-tuple-v.bal",
	"subset8/08-semtype/fixed-length-array-tuple2-v.bal",
	"subset8/08-semtype/fixed-length-array-v.bal",
	"subset8/08-semtype/fixed-length-array2-v.bal",
	"subset8/08-semtype/proj6-v.bal",
	"subset8/08-semtype/proj9-v.bal",
	"subset8/08-tuple/comp9-v.bal",

	// Migrated test uses a feature pi does not yet support in this stage.
	"subset8/08-error/check3-v.bal",
	"subset8/08-fill/chain2-v.bal",
	"subset8/08-fill/fill2-v.bal",
	"subset8/08-fill/fill3-v.bal",
	"subset8/08-fill/fill4-p.bal",
	"subset8/08-fill/fill7-v.bal",
	"subset8/08-future/fieldexpr1-v.bal",
	"subset8/08-future/never-v.bal",
	"subset8/08-mapping/5-v.bal",
	"subset8/08-nested/exact1-p.bal",
	"subset8/08-nested/proj1-p.bal",
	"subset8/08-nested/push1-v.bal",
	"subset8/08-rest/construct7-v.bal",
	"subset8/08-rest/exact1-p.bal",
	"subset8/08-semtype/optional-field-record1-v.bal",
	"subset8/08-semtype/optional-field-record3-v.bal",
	"subset8/08-semtype/readonly-record-field-v.bal",
	"subset8/08-semtype/readonly-record-field2-v.bal",
	"subset8/08-semtype/record-proj-v.bal",
	"subset8/08-singleton/proj4-v.bal",
	"subset8/08-tuple/push2-v.bal",
	"subset8/08-tuple/tupleunion1-v.bal",
	"subset8/08-union/construct4-v.bal",

	// Runtime panic in this stage on the migrated test.
	"subset8/08-bug/charcast1-v.bal",
	"subset8/08-bug/charcast2-v.bal",
	"subset8/08-error/10-v.bal",
	"subset8/08-error/check7-p.bal",
	"subset8/08-future/lib1-v.bal",
	"subset8/08-future/xmlsubtype-v.bal",
	"subset8/08-semtype/array-v.bal",
	"subset8/08-semtype/recurse-v.bal",
	"subset8/08-semtype/xml-complex-ro-v.bal",
	"subset8/08-semtype/xml-complex-rw-v.bal",
	"subset8/08-semtype/xml-never-v.bal",
	"subset8/08-semtype/xml-readonly-v.bal",
	"subset8/08-semtype/xml-sequence-v.bal",
	"subset8/08-string/10-v.bal",
	"subset8/08-string/11-v.bal",
	"subset8/08-string/12-v.bal",
	"subset8/08-string/13-v.bal",
	"subset8/08-string/15-v.bal",
	"subset8/08-string/16-v.bal",
	"subset8/08-string/17-v.bal",

	// Table-type descriptors not yet supported.
	"subset8/08-semtype/anydata-v.bal",
	"subset8/08-semtype/table-readonly-v.bal",
	"subset8/08-semtype/table-v.bal",
	"subset8/08-semtype/table2-v.bal",
	"subset8/08-semtype/table3-v.bal",
}

func TestTypeResolver(t *testing.T) {
	flag.Parse()

	testPairs := test_util.GetValidAndPanicTests(t, test_util.AST)

	for _, testPair := range testPairs {
		t.Run(testPair.Name, func(t *testing.T) {
			t.Parallel()
			testTypeResolution(t, testPair)
		})
	}
}

func testTypeResolution(t *testing.T, testCase test_util.TestCase) {
	for _, skip := range typeResolverSkipList {
		if test_util.HasPathSuffix(testCase.InputPath, skip) {
			t.Skipf("Skipping type resolver test for %s", testCase.InputPath)
			return
		}
	}

	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("Type resolution panicked for %s: %v", testCase.InputPath, r)
		}
	}()

	env := context.NewCompilerEnvironment(semtypes.CreateTypeEnv(), false)
	cx := context.NewCompilerContext(env)
	result, err := testphases.RunPipeline(cx, testphases.PhaseTypeNarrowing, testCase.InputPath)
	if err != nil {
		t.Errorf("pipeline failed for %s: %v", testCase.InputPath, err)
		return
	}
	tyCtx := semtypes.ContextFrom(cx.GetTypeEnv())
	validator := &typeResolutionValidator{t: t, ctx: cx, tyCtx: tyCtx}
	ast.Walk(validator, result.Package)

	// If we reach here, type resolution completed without panicking
	t.Logf("Type resolution completed successfully for %s", testCase.InputPath)
}

type typeResolutionValidator struct {
	t     *testing.T
	ctx   *context.CompilerContext
	tyCtx semtypes.Context
}

func (v *typeResolutionValidator) Visit(node ast.BLangNode) ast.Visitor {
	if node == nil {
		return nil
	}

	// Validate that all BLangExpression nodes have their determined type set
	if expr, ok := node.(ast.BLangExpression); ok {
		determinedType := expr.GetDeterminedType()
		if determinedType == nil {
			v.t.Errorf("expression %T at %v does not have determined type set", expr, expr.GetPosition())
		}
		if semtypes.IsNever(determinedType) {
			v.t.Errorf("expression %T at %v has determined type NEVER", expr, expr.GetPosition())
		}

	}

	if nodeWithSymbol, ok := node.(ast.BNodeWithSymbol); ok {
		symbol := nodeWithSymbol.Symbol()
		// Skip constant symbols (kind: 1) since they're resolved during semantic analysis
		if v.ctx.SymbolKind(symbol) == model.SymbolKindConstant {
			return v
		}
		if v.ctx.SymbolType(symbol) == nil {
			// FIXME: get rid of this
			if _, ok := node.(*ast.BLangConstant); ok {
				// constants will get their type set during semantic analysis
				return v
			}
			v.t.Errorf("symbol %s (kind: %v) does not have type set for node %T",
				v.ctx.SymbolName(symbol), v.ctx.SymbolKind(symbol), node)
		}
	}

	return v
}

func (v *typeResolutionValidator) VisitTypeData(typeData *model.TypeData) ast.Visitor {
	if typeData.TypeDescriptor == nil {
		return nil
	}
	if typeData.Type == nil {
		v.t.Errorf("type not resolved for %+v", typeData)
	}
	return v
}
