name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test ./...

      - name: Check gofmt
        run: |
          unformatted=$(gofmt -l -s .)
          if [ -n "$unformatted" ]; then
            echo "Unformatted Go files detected:"
            echo "$unformatted"
            exit 1
          fi

